# Generated by Django 4.2.1 on 2023-05-31 22:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameHistoryModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('score', models.FloatField()),
                ('difficulty', models.CharField(max_length=128)),
                ('matrixSize', models.IntegerField()),
                ('limitTime', models.IntegerField()),
                ('overTime', models.IntegerField()),
                ('finishedAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'game_history',
                'ordering': ['-finishedAt'],
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['createdAt'],
            },
        ),
    ]
