# Generated by Django 4.2.1 on 2023-05-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_usermodel_int_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='int_id',
            field=models.IntegerField(auto_created=True, default=int),
            preserve_default=False,
        ),
    ]
