# Generated by Django 4.2.1 on 2023-05-30 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_usermodel_int_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='int_id',
            new_name='intid',
        ),
    ]
