# Generated by Django 4.2.1 on 2023-05-30 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_int_id_usermodel_intid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='intid',
        ),
    ]
