# Generated by Django 4.2.1 on 2023-05-31 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_usermodel_intid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='last_login',
        ),
    ]
