# Generated by Django 4.2.1 on 2023-05-31 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_usermodel_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='fullname',
            new_name='name',
        ),
    ]
